import type { NextPage, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import { client } from '../services/prismicClient'
import useSWR from 'swr'
import ButtonSolid from '../components/Buttons/ButtonSolid'
import ButtonOutline from '../components/Buttons/ButtonOutline'
import SwiperHero from '../components/Swipers/SwiperHero'
import MediasButtons from '../components/Partials/MediasButtons'
import SectionSobre from '../components/Sections/SectionSobre'
import SectionServicos from '../components/Sections/SectionServicos'

// type inferedTypes = InferGetStaticPropsType<typeof getStaticProps>

const Home: NextPage = () => {
  const { data: servicosHome } = useSWR('getServicosHome', () =>
    client.getAllByType('servico')
  )

  return (
    <div className='relative'>
      <Head>
        <title>Camila Serra - Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SwiperHero />
      <SectionSobre />
      <SectionServicos />

      <MediasButtons />
      <main className="flex items-center justify-center flex-col gap-5 pt-4 h-screen">
        <h1>Em breve | shortly | 間もなく</h1>
      </main>
    </div>
  )
}

export default Home
