import type { NextPage, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import { client } from '../services/prismicClient'
import useSWR from 'swr'
import ButtonSolid from '../components/Buttons/ButtonSolid'
import ButtonOutline from '../components/Buttons/ButtonOutline'
import SwiperHero from '../components/Swipers/SwiperHero'
import SocialMediaButtons from '../components/Partials/SocialMediaButtons'

// type inferedTypes = InferGetStaticPropsType<typeof getStaticProps>

const Home: NextPage = () => {
  const { data: bannersHome } = useSWR('banners_da_home', () =>
    client.getSingle('banners_da_home')
  )

  return (
    <div>
      <Head>
        <title>CS Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SwiperHero />
      <SocialMediaButtons />
      <main className="flex items-center justify-center flex-col gap-5 pt-4 h-screen">
        <h1>Em breve | shortly | 間もなく</h1>
        <ButtonSolid>Button Solid</ButtonSolid>
        <ButtonOutline>Button Outline</ButtonOutline>
      </main>
    </div>
  )
}

export default Home
